import { Alert, Button, Group, Modal, Pagination, Stack, Text, Textarea, TextInput, Title } from "@mantine/core";
import { IconHeart, IconPlus, IconSun } from "@tabler/icons-react";
import { useState } from "react";
import { AppShell } from "./components/AppShell";
import { PromptDetailsModal } from "./features/prompts/PromptDetailsModal";
import { PromptGrid } from "./features/prompts/PromptGrid";
import { PromptSearch } from "./features/prompts/PromptSearch";
import type { Prompt } from "./lib/api.types";
import { usePromptCatalog } from "./features/prompts/usePromptCatalog";

export default function App() {
  const catalog = usePromptCatalog(); const [selected, setSelected] = useState<Prompt | null>(null); const [createOpen, setCreateOpen] = useState(false);
  return <AppShell><Stack gap="xl" className="library-page"><Group justify="space-between" align="flex-end" className="library-hero"><div><Title order={1}>Minha biblioteca</Title><Text c="dimmed">Organize, encontre e reutilize seus melhores prompts.</Text></div><Group gap="sm"><Button variant="subtle" className="theme-button" aria-label="Alternar tema"><IconSun size={17} /></Button><Button leftSection={<IconPlus size={16} />} onClick={() => setCreateOpen(true)}>Novo prompt</Button></Group></Group><PromptSearch value={catalog.filters.search} onChange={(search) => catalog.changeFilters({ search })} /><div className="filter-pills"><button className={!catalog.filters.categoryId ? "active" : ""} onClick={() => catalog.changeFilters({ categoryId: undefined })}>Todos</button>{catalog.taxonomy.categories.slice(0, 5).map((item) => <button key={item.id} className={catalog.filters.categoryId === item.id ? "active" : ""} onClick={() => catalog.changeFilters({ categoryId: item.id })}>{item.name}</button>)}<span /> <button className={catalog.filters.favorite ? "active" : ""} onClick={() => catalog.changeFilters({ favorite: catalog.filters.favorite ? undefined : true })}><IconHeart size={14} /> Favoritos</button></div>{catalog.error && <Alert color="red" title="Erro ao carregar" withCloseButton onClose={catalog.retry}>{catalog.error}</Alert>}<PromptGrid prompts={catalog.page.data} loading={catalog.loading} onOpen={setSelected} onToggleFavorite={(prompt) => void catalog.toggleFavorite(prompt)} onCopy={(prompt) => void catalog.copyPrompt(prompt)} /><Pagination total={catalog.page.pagination.totalPages} value={catalog.filters.page} onChange={(page) => catalog.changeFilters({ page })} /><PromptDetailsModal prompt={selected} opened={selected !== null} onClose={() => setSelected(null)} onCopy={(prompt) => void catalog.copyPrompt(prompt)} /><Modal opened={createOpen} onClose={() => setCreateOpen(false)} title="Create New Prompt" centered size="lg" classNames={{ content: "create-modal", header: "create-modal-header", title: "create-modal-title" }}><Stack><TextInput label="Title" placeholder="e.g., Code Review Assistant" /><Textarea label="Content" placeholder="Enter your prompt text here..." minRows={8} autosize /><Group grow><TextInput label="Category" placeholder="Select Category" /><TextInput label="Subcategory" placeholder="Select Subcategory" /></Group><TextInput label="Tags" placeholder="Add tags..." /><Group justify="flex-end"><Button variant="subtle" onClick={() => setCreateOpen(false)}>Cancelar</Button><Button onClick={() => setCreateOpen(false)}>Salvar prompt</Button></Group></Stack></Modal></Stack></AppShell>;
}
